version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "twardoch"
    assignees:
      - "twardoch"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
  
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "twardoch"
    assignees:
      - "twardoch"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"